server:
  port: 7000
spring:
  zipkin:
    base-url: http://101.37.117.226:9411/  #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0  #采样的百分比
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 101.37.117.226:8848 # 将gateway注册到nacos
    gateway:
      discovery:
        locator:
          enabled: true # 让gateway从nacos中获取服务信息
          #默认 http://localhost:7000/service-product/product/1
      routes:
        - id: product_route
          uri: lb://service-product
          order: 1
          predicates:
            - Path=/product-serv/**
            - Method=GET
          #  - Pid=0,5
          filters:
            - StripPrefix=1
            - SetStatus=250
         #  - Log=true,false
        - id: order_route
          uri: lb://service-order
          order: 1
          predicates:
            - Path=/order-serv/**
          filters:
            - StripPrefix=1

# http://localhost:8081/product/1--http://localhost:7000/product-serv/product/1