server:
  port: 8091
  tomcat:
    max-threads: 2
spring:
  zipkin:
    base-url: http://101.37.117.226:9411/  #zipkin server的请求地址
    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0  #采样的百分比
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.37.117.226:3333/shop?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: cba123456cba
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      discovery:
        server-addr: 101.37.117.226:8848
    sentinel:
      transport:
        port: 9999 #跟控制台交流的端口,随意指定一个未使用的端口即可
        dashboard: 101.37.117.226:8111 # 指定控制台服务的地址
        #     filter:
           #    enabled: false
service-product: # 调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


# 开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true
